### ISSUE TITLE
pub conflict when including serializable in angular2 project

### ISSUE THREAD

**Issue by hentoesch** [dart-league/serializable#1]
when i use the package in a angular 2 project i get the following error:

Package build_runner has no versions that match >=0.1.1 <0.2.0 derived from:
- serializable 0.0.2 depends on version ^0.1.1

steps to reproduce:

1.) create web-angular app with stagehand
2.) add serializable to pubspec.yaml (serializable:	^0.0.2)
3.) run pub get

it works in a standalone library project.

**Comment by luisvt** [comment]
Thanks let me check

**Comment by luisvt** [comment]
The problem is caused by `angular2`. This is caused because `angular2 v2.2.0` is using: `build v0.5.0` as maximum, while serializable is using `0.6.3` which is a newer version. To resolve the issue you can wait until `angular 2 v2.3.0` to arrive or add next code to the `pubspec.yaml` to workaround the issue in the meanwhile:

```yaml
dependency_overrides:
    build: ^0.6.3
```

**Comment by hentoesch** [comment]
cool. it works with my project now. thanks a lot.
